on:
  push:
    branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
      
        # step 1: Checkout GitHub Action
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
      
        # step 2: Docker login        
        - name: 'Docker login'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER}}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
            
        # step 3: Build Docker Image  
        - name: Build Docker
          run: docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER}}/myimage:${{ github.sha }}
        
        # step 4: Push Docker to Azure Registry  
        - name: Push Docker
          run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER}}/myimage:${{ github.sha }}
